services:
  - type: web
    name: user-access-control-demo
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: PORT
        value: 8080
