name: Publish

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Version to publish
        required: true
        default: 2.0.0

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish GitHub Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: https://gradle.com/terms-of-service
          build-scan-terms-of-use-agree: 'yes'

      - name: Publish to GitHub Packages
        run: ./gradlew clean build jacocoTestReport publish -PreleaseVersion="${RELEASE_VERSION}" --scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.event.release.tag_name || inputs.releaseVersion }}
